export enum InputType {
  text = "Text",
  button = "Button",
  checkbox = "Checkbox",
  color = "Color",
  date = "Date",
  "datetime-local" = "Datetime local",
  email = "Email",
  file = "File",
  hidden = "Hidden",
  image = "Image",
  month = "Month",
  number = "Number",
  password = "Password",
  radio = "Radio",
  range = "Range",
  reset = "Reset",
  search = "Search",
  submit = "Submit",
  tel = "Telephone",
  time = "Time",
  url = "URL",
  week = "Week",
}
